# -*- coding: utf-8 -*-
"""Feedforward.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LThE29CSH0X_ueCMM1ph_SZ4a7XD3n8o
"""

# !pip install torchinfo

import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
from torchinfo import summary

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Hyper-parameters
input_size = 28*28 # MNIST image
hidden_size = 500
num_classes = 10
num_epochs = 5
batch_size = 100
learning_rate = 0.001

# Download MNIST dataset
train_dataset = torchvision.datasets.MNIST(root='data',
                                           train=True,
                                           transform=transforms.ToTensor(),
                                           download=True)

test_dataset = torchvision.datasets.MNIST(root='data',
                                          train=False,
                                          transform=transforms.ToTensor())

# Data Loader
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=batch_size,
                                           shuffle=True)
test_loader = torch.utils.data.DataLoader(dataset=test_dataset,
                                          batch_size=batch_size,
                                          shuffle=False)

item = next(x for x in train_loader)
item[0].shape

device

# Fully connected neural network with 1 hidden layer
class LeNetCNN(nn.Module):
  def __init__(self, input_size, hidden_size, num_classes):
    super(LeNetCNN, self).__init__()

    '''
    To Convert image 28x28 to 32x32 (for LeNet)
    For an input image of size 28x28, padding 2 pixels to all sides
    increases both HEIGHT and WIDTH by 4 (2 pixels on each end):

    New size=28+2×2=32
    '''
    self.conv1 = nn.Conv2d(in_channels=1, out_channels=6,  # only 1 color channel
                           kernel_size=(5,5), stride=1, padding=2)
    self.conv2 = nn.Conv2d(in_channels=6, out_channels=16,
                           kernel_size=(5,5), stride=1)
    self.conv3 = nn.Conv2d(in_channels=16, out_channels=120,
                           kernel_size=(5,5), stride=1)

    self.tanh = nn.Tanh()
    self.avgpool = nn.AvgPool2d(kernel_size=2, stride=2)


    self.fc1 = nn.Linear(120, out_features=84) # Initilize `class Linear(Module):`
    # self.relu = nn.ReLU() # Intialize Relu object
    self.fc2 = nn.Linear(84, num_classes) # Initilize Linear object

  def forward(self, x):
    '''
    def linear(
        input: Tensor,
        weight: Tensor,
        .....
    ) -> Tensor:
    '''
    out = self.conv1(x)
    out = self.tanh(out)
    out = self.avgpool(out)

    out = self.conv2(out)
    out = self.tanh(out)
    out = self.avgpool(out)

    out = self.conv3(out)
    out = self.tanh(out)

    out = out.reshape(out.size(0),-1)
    out = self.fc1(out)
    out = self.tanh(out) # Out: Tensor
    out = self.fc2(out) # Out: Tensor

    return out

model = LeNetCNN(input_size, hidden_size, num_classes).to(device)
summary(model, input_size=(100, 1, 28, 28)) # (batch_size, channels, height, width)

# Intilize Loss and Optimizer
criterion = nn.CrossEntropyLoss() # Intialize Loss object (e.g CrossEntropy, MSE, etc)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate) # Intilize Optimizer object (e.g SGD, Adam, etc)

# Train the model
total_step = len(train_loader)
for epoch in range(num_epochs):
  for i, (images, labels) in enumerate(train_loader): # multiple images because train_loader loads by batches (e.g 32 images)
    # 1) Move tensors to the configured device
    # Input: ( N, Color, Height, Width ) or ( Color, Height, Width)
    # images = images.reshape(-1, 1, 32, 32).to(device) # 32 by 32 by COLOR_CHANNEL=1
    images = images.to(device)
    labels = labels.to(device)

    # 2) Forward pass
    # - Compute prediction
    preds = model(images)
    # - Compute Loss
    loss = criterion(preds, labels)

    # 3) Backward (Compute Gradient) and optimize
    # Compute gradient via backpropagation
    optimizer.zero_grad() # Reset the gradient, only use gradient on current batch
    loss.backward()
    # Update model parameters
    optimizer.step()

    if (i+100) % 100 == 0: # Every 100 batches
      print(f'Epoch [{epoch}/{num_epochs}], Step [{i}/{total_step}], Loss: {loss.item():.4f}')

item = next(x for x in test_loader)
item[0].shape

# Test the model
# In test phase, we don't need to compute gradients (for memory efficiency)
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print('Accuracy of the network on the 10000 test images: {} %'.format(100 * correct / total))

# Save the model checkpoint
torch.save(model.state_dict(), 'model.ckpt')

